spring:
  application:
    name: training-event-management-system-back

  datasource:
    url: jdbc:postgresql://localhost:5432/training-event-management-system
    username: postgres
    password: Andrewalissa21

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
